version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - pwd
      - ls -al
      - which composer
      - whoami
      - echo $COMPOSER_ALLOW_SUPERUSER
      - export COMPOSER_ALLOW_SUPERUSER="1"
      - echo $COMPOSER_ALLOW_SUPERUSER
      - export COMPOSER_NO_INTERACTION="1"
      - uname -a
      - cat /etc/lsb-release
      - apt-get update -y
      - apt-get upgrade -y
      - apt-get install -y php7.2
      - composer install
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - cp .env.example .env
      - php artisan key:generate
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - php vendor/bin/phpunit --testdox
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
